import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HeroSection from '../components/Home/Index'
import { postFileNames, postsPath } from '../utils/mdxUtils'
import matter from 'gray-matter'

export default function Home({ posts }) {
  console.log(posts);

  return (
    <>
      <Head>
        <title>Next Js Mdx | AzizBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
    </>

  )
};

export async function getStaticProps() {
  const posts = postFileNames?.map((slug) => {
    const content = fs.readFileSync(path.join(postsPath, `${slug}`));
    const { data } = matter(content);

    return {
      frontmatter: data,
      slug: slug.replace(/\.mdx?$/, ''),
    }
  });

  return {
    props: {
      posts: JSON.parse(JSON.stringify(posts))
    }
  }
};
